name: Docker Build and Push

on:
  push:
    branches:
      - main   # Runs only on push to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t deepikakripanithi/myapp:latest .

      - name: Push Docker image
        run: docker push deepikakripanithi/myapp:latest
